### ISSUE TITLE
Windows cannot start the Docker Engine service on local computer error 1067

### ISSUE THREAD

**Issue by eliassal** [Microsoft/Virtualization-Documentation#439]
Hi I have a win10 with HYper-V already enabled I have followed instructions at 
 https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10
Docker Engine is not starting, in event viewer it says:

fatal: Error starting daemon: open C:\ProgramData\docker\docker.pid: The system cannot find the path specified

I created a Docker directory in ProgramData, docker service started

**Comment by jhowardmsft** [comment]
See https://github.com/Microsoft/Virtualization-Documentation/pull/438#issuecomment-255765173. Working on a fix.

**Comment by friism** [comment]
I've sent a pull to not make people install some random CI build: https://github.com/Microsoft/Virtualization-Documentation/pull/440

**Comment by eliassal** [comment]
Thanks, Can you please let me know where those containers are stocked when we do a docker pull or run in windows? I imagine that they are created in the c drive

**Comment by jhowardmsft** [comment]
They follow the root directory of the daemon configuration. By default that's c:\programdata\docker. From the command line you can do something like `dockerd -g c:\somepath` to relocate to somewhere else, or you can use the `graph` option in the daemons json configuration such as

```
{
    "graph":  "C:\\somepath"
}
```

**Comment by eliassal** [comment]
Thanks,
I looked into `%programdata%\docker\config\ no daemon.json file exists omly keys.json
 I searched all my C drive no file exists with the name daemon.json 
Regards

**Comment by eliassal** [comment]
Also another question if you allow, I did an ipconfig on the microsoft/nano, I get
IPv4 Address. . . . . . . . . . . : 172.31.7.184
Subnet Mask . . . . . . . . . . . : 255.255.240.0
Default Gateway . . . . . . . . . : 172.31.0.1
I would like that my containers have the same subnet details where my other test machines run 192.168.1.0, how this cna be changed? how those networking details are attributed to the container?

**Comment by PatrickLang** [comment]
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/container_networking#network-creation

You can create a different network or reconfigure it to use another IP space

**Comment by eliassal** [comment]
The article is clear but feedback is not possible there, when I do Get-NetAdapter, I get

Name                                     InterfaceDescription                    
----                                         --------------------                    
vEthernet (HNS Interna...          Hyper-V Virtual Ethernet Adapter #2    
vEthernet (Internal Et...             Hyper-V Virtual Ethernet Adapter #3    
vEthernet (External)                   Hyper-V Virtual Ethernet Adapter       
Wi-Fi                                          Intel(R) Dual Band Wireless-AC 3165        
StartechAdap                            Realtek USB GbE Family Controller         

I tried both vEthernet (External)  & StartechAdap as the names of the adapter as follows, 
docker network create -d transparent -o com.docker.network.windowsshim.interface="vEthernet (External)" TransparentNetS
docker network create -d transparent -o com.docker.network.windowsshim.interface="StartechAdap" TransparentNetSalam

it erros with tis
Error response from daemon: HNS failed with error : Element not found.

It seems that once docker was installed, 2 NAT were created in Hyper-V switches, one is internal only on the wifi ard, 2nd private network

I am completely confused? Should I delete thos 2 NAts? why it is not recognizing the external interface?

**Comment by eliassal** [comment]
Patrick, I am also facing another issue on a win2K16 (a VM) where I have followed instructions at 
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server

I started dockerd on the server which started fine but issuing the commande 
docker run -it microsoft/nanoserver cmd

I get 

Unable to find image 'microsoft/nanoserver:latest' locally
latest: Pulling from microsoft/nanoserver

C:\Program Files\Docker\docker.exe: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/
v2/blobs/sha256/e1/e14bc0ecea1239316be8996be84ce0664740fc1c24905d9c82aeeac6e8381cf8/data?Expires=1477336162&Signature=NkVYhJ0kO0TXmw6zzr~AqG
lYB5hyOGJc7PHVc7wlEjz9Flx7orY7Dp9uD~bo0sL3JZNd9kBYpVp7t6XPwRW5kclH6HASPq2iNPbXiCljBpH8wJNq8OFNyMSf~PgUfLM3vwSCI31Ac3qoXOf1AydZ84gaHmrDtw-MPO
OVscynf~c_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 52.85.221.42:443: i/o timeout.

Any idea please?

**Comment by eliassal** [comment]
Hi, hold a moment, just issued the command  Get-ContainerNetwork, I have 

Name     Id                                   Subnets         Mode        SourceMac DNSServers DNSSuffix
----     --                                   -------         ----        --------- ---------- ---------
nat      ff909283-0245-4a82-a407-a37fbc872fbb {172.31.0.0/20} NAT
External 52ba3cec-f2a4-41d8-af88-21cd9086ebde                 Transparent

So, how I can force docker not to use the nat one as it seems it is the default?

**Comment by jhowardmsft** [comment]
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/container_networking#transparent-network

**Comment by jhowardmsft** [comment]
Original issue fixed by https://github.com/docker/docker/pull/27690

**Comment by eliassal** [comment]
Thanks, on win 10 it is working like a charm but not on win 2K16 without HYper-V, still getting

PS C:\Users\salam> docker pull microsoft/windowsservercore:10.0.14393.321
10.0.14393.321: Pulling from microsoft/windowsservercore
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/93/93a9c37b36d03323f7b8fd
d7f0302f7e487a0e8b31ccd8e689c40a404d2f1ea9/data?Expires=1477422263&Signature=f~Mp4jYaEW-0MMnCgGvGvlfWW5-5XNge0G98LCW9rO~jF3YO5KvoRPJJb6V4eZreg0me
M~fgh~~9XzTpIBkDDHRczRVBGzju-cKLiw0S6VcGDEWAmAg2Ttmz7EwsXXB6ILP4ODwqOn8lrsK6va1IUxZk0y8LLav1bQ39wsSeUIs_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial t
cp 54.192.129.122:443: i/o timeout
